# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'onkourse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onkourse

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  target 'onkourseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'onkourse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onkourse-tvOS

  target 'onkourse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
